name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linux:
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
          - target: aarch64-unknown-linux-gnu
            deps: apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

    name: Build ${{ matrix.target }}
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      
      - name: Install Essentials
        run: |
          apt-get update -y
          apt-get upgrade -y
          apt-get install -y curl gcc g++ cmake openjdk-17-jdk-headless
      
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      
      - name: Install linker dependencies
        if: ${{ matrix.deps != '' }}
        run: ${{ matrix.deps }}
      
      - name: Run Gradle Build
        run: ./gradlew build -Ptarget=${{ matrix.target }}

  windows:
    strategy:
      matrix:
        include:
          - target: x86_64-pc-windows-msvc
          - target: aarch64-pc-windows-msvc

    name: Build ${{ matrix.target }}
    runs-on: windows-2022
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      
      - name: Run Gradle Build
        run: ./gradlew build -Ptarget=${{ matrix.target }}

  macos:
    name: Build macOS universal binary
    runs-on: macos-14
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install CMake
        run: |
          brew upgrade cmake || brew install cmake
          cmake --version

      - name: Compile natives
        run: |
          rustup target add x86_64-apple-darwin
          cargo build --release --target=x86_64-apple-darwin
          rustup target add aarch64-apple-darwin
          cargo build --release --target=aarch64-apple-darwin

      - name: Create target directory for darwin
        run: mkdir -p target/darwin/release

      - name: Combine to universal dylib
        run: lipo -create -output target/darwin/release/libconnector.dylib target/**/release/*.dylib

      - name: Run Gradle Build
        run: ./gradlew build -Ptarget=darwin -x cargoBuild
