name: Publish

on:
  push:
    branches: [ main ]
  release:
    types: [ published ]

concurrency:
  group: "publish"
  cancel-in-progress: true

jobs:
  # Wait for build workflow to complete
  wait-for-build:
    name: Wait for build to complete
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Linux x86_64 build
        uses: lewagon/wait-on-check-action@v1.3.4
        with:
          ref: ${{ github.sha }}
          check-name: 'Build x86_64-unknown-linux-gnu'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
      
      - name: Wait for Linux aarch64 build
        uses: lewagon/wait-on-check-action@v1.3.4
        with:
          ref: ${{ github.sha }}
          check-name: 'Build aarch64-unknown-linux-gnu'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
      
      - name: Wait for Windows x86_64 build
        uses: lewagon/wait-on-check-action@v1.3.4
        with:
          ref: ${{ github.sha }}
          check-name: 'Build x86_64-pc-windows-msvc'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
      
      - name: Wait for Windows ARM64 build
        uses: lewagon/wait-on-check-action@v1.3.4
        with:
          ref: ${{ github.sha }}
          check-name: 'Build aarch64-pc-windows-msvc'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
      
      - name: Wait for macOS build
        uses: lewagon/wait-on-check-action@v1.3.4
        with:
          ref: ${{ github.sha }}
          check-name: 'Build macOS universal binary'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

  linux:
    needs: wait-for-build
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
          - target: aarch64-unknown-linux-gnu
            deps: apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

    name: Publish ${{ matrix.target }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    container:
      image: ubuntu:22.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      
      - name: Install Essentials
        run: |
          apt-get update -y
          apt-get upgrade -y
          apt-get install -y curl gcc g++ cmake openjdk-17-jdk-headless
      
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      
      - name: Install linker dependencies
        if: ${{ matrix.deps != '' }}
        run: ${{ matrix.deps }}
      
      - name: Build and Publish
        run: ./gradlew publish -Ptarget=${{ matrix.target }}
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  windows:
    needs: wait-for-build
    strategy:
      matrix:
        include:
          - target: x86_64-pc-windows-msvc
          - target: aarch64-pc-windows-msvc

    name: Publish ${{ matrix.target }}
    runs-on: windows-2022
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      
      - name: Build and Publish
        run: ./gradlew publish -Ptarget=${{ matrix.target }}
        env:
          GITHUB_ACTOR: ${{ env.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  macos:
    needs: wait-for-build
    name: Publish macOS universal binary
    runs-on: macos-14
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install CMake
        run: |
          brew upgrade cmake || brew install cmake
          cmake --version

      - name: Compile natives
        run: |
          rustup target add x86_64-apple-darwin
          cargo build --release --target=x86_64-apple-darwin
          rustup target add aarch64-apple-darwin
          cargo build --release --target=aarch64-apple-darwin

      - name: Create target directory for darwin
        run: mkdir -p target/darwin/release

      - name: Combine to universal dylib
        run: lipo -create -output target/darwin/release/libconnector.dylib target/**/release/*.dylib

      - name: Build and Publish
        run: ./gradlew publish -Ptarget=darwin -x cargoBuild
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
